# Ignore everything
*
# Allow list
## Frontend
!components/
!games/
!i18n/
!pages/
!public/
!jsconfig.json
!LICENSE
!next.config.js
!package-lock.json
!package.json
!postcss.config.js
!styles.css
!tailwind.config.js
!backend/server.js
!backend/load-game.js

## Backend
!backend/api/
!backend/go.mod
!backend/go.sum
!backend/main.go

## Scripts
!docker/allinone/
!dev/
