#!/usr/bin/env ruby
require 'optparse'
require_relative 'csv_parser'

$opt = {
  fastmoney: true,
  rounds: 6,
  random: true,
  multipler: true,
  ignore_header: false
}

OptionParser.new do |opts|
  opts.banner = "Usage: csv_parser -[nmsidv] \n Generate realistic point values for game questions"
  opts.on('--no-fast-money', 'Should fast money rounds be generated') do 
    $opt[:fastmoney] = false
  end
  opts.on('--ignore-header', 'ignore the header on csv files') do 
    $opt[:ignore_header] = true
  end

  opts.on('--no-random', 'do not suffle rounds around and go in order of reading') do 
    $opt[:random] = false
  end
  opts.on('--no-multiplyer', 'do not create double point rounds half way through the game') do 
    $opt[:multipler] = false
  end
  opts.on('-rNUM','--rounds=NUM',  Integer, 'How many rounds per a game') do |r|
    $opt[:rounds] = r
  end

  opts.on('-v', 'Verbose Mode')
end.parse!(into: $opt)

csv_parser = CSVParser.new({
  fastmoney: $opt[:fastmoney],
  rounds: $opt[:rounds],
  random: $opt[:random],
  multipler: $opt[:multipler],
  ignore_header: $opt[:ignore_header],
  verbose: $opt[:v],
  files: ARGV
})

csv_parser.parse
